server/flow/ruby/config/routes.rb
# frozen_string_literal: true

require 'sidekiq_unique_jobs/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  root 'home#index'

  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  get 'health', to: 'health#show'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/nodeinfo', to: 'well_known/nodeinfo#index', as: :nodeinfo, defaults: { format: 'json' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/change-password', to: redirect('/auth/edit')
  get '.well-known/keybase-proof-config', to: 'well_known/keybase_proof_config#show'

  get '/nodeinfo/2.0', to: 'well_known/nodeinfo#show', as: :nodeinfo_schema

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }
  get 'intent', to: 'intents#show'
  get 'custom.css', to: 'custom_css#show', as: :custom_css

  resource :instance_actor, path: 'actor', only: [:show] do
    resource :inbox, only: [:create], module: :activitypub
    resource :outbox, only: [:show], module: :activitypub
  end

  devise_scope :user do
    get '/invite/:invite_code', to: 'auth/registrations#new', as: :public_invite

    namespace :auth do
      resource :setup, only: [:show, :update], controller: :setup
      resource :challenge, only: [:create], controller: :challenges
      get 'sessions/security_key_options', to: 'sessions#webauthn_options'
    end
  end

  devise_for :users, path: 'auth', controllers: {
    omniauth_callbacks: 'auth/omniauth_callbacks',
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/authorize_follow', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }

  resources :accounts, path: 'users', only: [:show], param: :username do
    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end

      resources :replies, only: [:index], module: :activitypub
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    resource :outbox, only: [:show], module: :activitypub
    resource :inbox, only: [:create], module: :activitypub
    resource :claim, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
    resource :followers_synchronization, only: [:show], module: :activitypub
  end

  resource :inbox, only: [:create], module: :activitypub

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:username/with_replies', to: 'accounts#show', as: :short_account_with_replies
  get '/@:username/media', to: 'accounts#show', as: :short_account_media
  get '/@:username/tagged/:tag', to: 'accounts#show', as: :short_account_tag
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status
  get '/@:account_username/:id/embed', to: 'statuses#embed', as: :embed_short_account_status

  get  '/interact/:id', to: 'remote_interaction#new', as: :remote_interaction
  post '/interact/:id', to: 'remote_interaction#create'

  get '/explore', to: 'directories#index', as: :explore
  get '/settings', to: redirect('/settings/profile')

  namespace :settings do
    resource :profile, only: [:show, :update] do
      resources :pictures, only: :destroy
    end

    get :preferences, to: redirect('/settings/preferences/appearance')

    namespace :preferences do
      resource :appearance, only: [:show, :update], controller: :appearance
      resource :notifications, only: [:show, :update]
      resource :other, only: [:show, :update], controller: :other
    end

    resource :import, only: [:show, :create]
    resource :export, only: [:show, :create]

    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
      resources :lists, only: :index, controller: :lists
      resources :domain_blocks, only: :index, controller: :blocked_domains
      resources :bookmarks, only: :index, controller: :bookmarks
    end

    resources :two_factor_authentication_methods, only: [:index] do
      collection do
        post :disable
      end
    end

    resource :otp_authentication, only: [:show, :create], controller: 'two_factor_authentication/otp_authentication'

    resources :webauthn_credentials, only: [:index, :new, :create, :destroy],
              path: 'security_keys',
              controller: 'two_factor_authentication/webauthn_credentials' do

      collection do
        get :options
      end
    end

    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :identity_proofs, only: [:index, :new, :create, :destroy]

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]
    resource :migration, only: [:show, :create]

    namespace :migration do
      resource :redirect, only: [:new, :create, :destroy]
    end

    resources :aliases, only: [:index, :create, :destroy]
    resources :sessions, only: [:destroy]
    resources :featured_tags, only: [:index, :create, :destroy]
    resources :login_activities, only: [:index]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]
  resource :relationships, only: [:show, :update]
  resource :statuses_cleanup, controller: :statuses_cleanup, only: [:show, :update]

  get '/public', to: 'public_timelines#show', as: :public_timeline
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :domain_allows, only: [:new, :create, :show, :destroy]
    resources :domain_blocks, only: [:new, :create, :show, :destroy, :update, :edit]

    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]

    resources :announcements, except: [:show] do
      member do
        post :publish
        post :unpublish
      end
    end

    resource :settings, only: [:edit, :update]
    resources :site_uploads, only: [:destroy]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ } do
      member do
        post :clear_delivery_errors
        post :restart_delivery
        post :stop_delivery
      end
    end

    resources :rules

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :destroy] do
      member do
        post :enable
        post :unsensitive
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :relationships, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role, only: [] do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
      resource :sign_in_token_authentication, only: [:create, :destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :ip_blocks, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]
    resource :follow_recommendations, only: [:show, :update]

    resources :tags, only: [:index, :show, :update] do

server/flow/ruby/app/views/layouts/admin.html.haml
- content_for :header_tags do
  = render_initial_state
  = javascript_pack_tag 'public', crossorigin: 'anonymous'

- content_for :content do
  .admin-wrapper
    .sidebar-wrapper
      .sidebar-wrapper__inner
        .sidebar
          = link_to root_path do
            = image_pack_tag 'logo.svg', class: 'logo', alt: 'Flow'

          .sidebar__toggle
            .sidebar__toggle__logo
              = link_to root_path do
                = svg_logo_full

            = link_to '#', class: 'sidebar__toggle__icon' do
              = fa_icon 'bars'

          = render_navigation

    .content-wrapper
      .content
        .content-heading
          %h2= yield :page_title

          - if :heading_actions
            .content-heading-actions
              = yield :heading_actions

        = render 'application/flashes'

        = yield

    .sidebar-wrapper.sidebar-wrapper--empty

= render template: 'layouts/application'

server/flow/ruby/app/views/layouts/application.html.haml
!!! 5
%html{ lang: I18n.locale }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }/

    - if cdn_host?
      %link{ rel: 'dns-prefetch', href: cdn_host }/
      %meta{ name: 'cdn-host', content: cdn_host }/

    - if storage_host?
      %link{ rel: 'dns-prefetch', href: storage_host }/

    %link{ rel: 'icon', href: favicon_path, type: 'image/x-icon' }/
    %link{ rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' }/
    %link{ rel: 'mask-icon', href: '/mask-icon.svg', color: '#2B90D9' }/
    %link{ rel: 'manifest', href: '/manifest.json' }/
    %meta{ name: 'msapplication-config', content: '/browserconfig.xml' }/
    %meta{ name: 'theme-color', content: '#282c37' }/
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }/

    %title= content_for?(:page_title) ? safe_join([yield(:page_title).chomp.html_safe, title], ' - ') : title

    = stylesheet_pack_tag 'common', media: 'all', crossorigin: 'anonymous'
    = stylesheet_pack_tag current_theme, media: 'all', crossorigin: 'anonymous'
    = javascript_pack_tag 'common', crossorigin: 'anonymous'
    = javascript_pack_tag "locale_#{I18n.locale}", crossorigin: 'anonymous'
    = csrf_meta_tags
    %meta{ name: 'style-nonce', content: request.content_security_policy_nonce }

    = stylesheet_link_tag '/inert.css', skip_pipeline: true, media: 'all', id: 'inert-style'

    - if Setting.custom_css.present?
      = stylesheet_link_tag custom_css_path, host: request.host, media: 'all'

    = yield :header_tags

  %body{ class: body_classes }
    = content_for?(:content) ? yield(:content) : yield

    .logo-resources
      = raw render file: Rails.root.join('app', 'javascript', 'images', 'logo_transparent.svg')
      = raw render file: Rails.root.join('app', 'javascript', 'images', 'logo_full.svg')

server/flow/ruby/app/views/layouts/auth.html.haml
- content_for :header_tags do
  = javascript_pack_tag 'public', crossorigin: 'anonymous'

- content_for :content do
  .container-alt
    .logo-container
      %h1
        = link_to root_path do
          = svg_logo_full

    .form-container
      = render 'flashes'

      = yield

= render template: 'layouts/application'

server/flow/ruby/app/views/layouts/embedded.html.haml
!!! 5
%html{ lang: I18n.locale }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ name: 'robots', content: 'noindex' }/

    - if cdn_host?
      %link{ rel: 'dns-prefetch', href: cdn_host }/
      %meta{ name: 'cdn-host', content: cdn_host }/

    - if storage_host?
      %link{ rel: 'dns-prefetch', href: storage_host }/

    = stylesheet_pack_tag 'common', media: 'all', crossorigin: 'anonymous'
    = stylesheet_pack_tag Setting.default_settings['theme'], media: 'all', crossorigin: 'anonymous'
    = javascript_pack_tag 'common', integrity: true, crossorigin: 'anonymous'
    = javascript_pack_tag "locale_#{I18n.locale}", integrity: true, crossorigin: 'anonymous'
    = render_initial_state
    = javascript_pack_tag 'public', integrity: true, crossorigin: 'anonymous'
  %body.embed
    = yield

    .logo-resources
      = raw render file: Rails.root.join('app', 'javascript', 'images', 'logo_transparent.svg')

server/flow/ruby/app/views/layouts/error.html.haml
!!!
%html{ lang: I18n.locale }
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %meta{ charset: 'utf-8' }/
    %title= safe_join([yield(:page_title), Setting.default_settings['site_title']], ' - ')
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    = stylesheet_pack_tag 'common', media: 'all', crossorigin: 'anonymous'
    = stylesheet_pack_tag Setting.default_settings['theme'], media: 'all', crossorigin: 'anonymous'
    = javascript_pack_tag 'common', crossorigin: 'anonymous'
    = javascript_pack_tag 'error', crossorigin: 'anonymous'
  %body.error
    .dialog
      .dialog__illustration
        %img{ alt: Setting.default_settings['site_title'], src: '/oops.png' }/
      .dialog__message
        %h1= yield :content

server/flow/ruby/app/views/layouts/modal.html.haml
- content_for :header_tags do
  = javascript_pack_tag 'public', crossorigin: 'anonymous'

- content_for :content do
  - if user_signed_in? && !@hide_header
    .account-header
      .avatar= image_tag current_account.avatar.url(:original)
      .name
        = t 'users.signed_in_as'
        %span.username @#{current_account.local_username_and_domain}
      = link_to destroy_user_session_path(continue: true), method: :delete, class: 'logout-link icon-button' do
        = fa_icon 'sign-out'

  .container-alt= yield
  .modal-layout__mastodon
    %div
      %img{alt:'', draggable:'false', src:"#{mascot_url}"}

= render template: 'layouts/application'

server/flow/ruby/app/views/layouts/plain_mailer.html.haml
= yield

server/flow/ruby/app/views/layouts/public.html.haml
- content_for :header_tags do
  = render_initial_state
  = javascript_pack_tag 'public', crossorigin: 'anonymous'

- content_for :content do
  .public-layout
    - unless @hide_navbar
      .container
        %nav.header
          .nav-left
            = link_to root_url, class: 'brand' do
              = svg_logo_full

            - unless whitelist_mode?
              = link_to t('directories.directory'), explore_path, class: 'nav-link optional' if Setting.profile_directory
              = link_to t('about.about_this'), about_more_path, class: 'nav-link optional'
              = link_to t('about.apps'), 'https://flow.join.imzqqq.top/apps', class: 'nav-link optional'

          .nav-center

          .nav-right
            - if user_signed_in?
              = link_to t('settings.back'), root_url, class: 'nav-link nav-button webapp-btn'
            - else
              = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn nav-link nav-button'
              = link_to t('auth.register'), available_sign_up_path, class: 'webapp-btn nav-link nav-button'

    .container= yield

    .container
      .footer
        .grid
          .column-0
            %h4= t 'footer.resources'
            %ul
              %li= link_to t('about.terms'), terms_path
              %li= link_to t('about.privacy_policy'), terms_path
          .column-1
            %h4= t 'footer.developers'
            %ul
              %li= link_to t('about.documentation'), 'https://flow.docs.imzqqq.top/'
              %li= link_to t('about.api'), 'https://flow.docs.imzqqq.top/client/intro/'
          .column-2
            %h4= link_to t('about.what_is_mastodon'), 'https://flow.join.imzqqq.top/'
            = link_to svg_logo, root_url, class: 'brand'
          .column-3
            %h4= site_hostname
            %ul
              - unless whitelist_mode?
                %li= link_to t('about.about_this'), about_more_path
              %li= "v#{Flow::Version.to_s}"
          .column-4
            %h4= t 'footer.more'
            %ul
              %li= link_to t('about.source_code'), Flow::Version.source_url
              %li= link_to t('about.apps'), 'https://flow.join.imzqqq.top/apps'

= render template: 'layouts/application'