server/flow/ruby/config/routes.rb
# frozen_string_literal: true

require 'sidekiq_unique_jobs/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  root 'home#index'

  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  get 'health', to: 'health#show'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/nodeinfo', to: 'well_known/nodeinfo#index', as: :nodeinfo, defaults: { format: 'json' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/change-password', to: redirect('/auth/edit')
  get '.well-known/keybase-proof-config', to: 'well_known/keybase_proof_config#show'

  get '/nodeinfo/2.0', to: 'well_known/nodeinfo#show', as: :nodeinfo_schema

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }
  get 'intent', to: 'intents#show'
  get 'custom.css', to: 'custom_css#show', as: :custom_css

  resource :instance_actor, path: 'actor', only: [:show] do
    resource :inbox, only: [:create], module: :activitypub
    resource :outbox, only: [:show], module: :activitypub
  end

  devise_scope :user do
    get '/invite/:invite_code', to: 'auth/registrations#new', as: :public_invite

    namespace :auth do
      resource :setup, only: [:show, :update], controller: :setup
      resource :challenge, only: [:create], controller: :challenges
      get 'sessions/security_key_options', to: 'sessions#webauthn_options'
    end
  end

  devise_for :users, path: 'auth', controllers: {
    omniauth_callbacks: 'auth/omniauth_callbacks',
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: lambda { |req| req.format.nil? || req.format.html? }
  get '/authorize_follow', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }

  resources :accounts, path: 'users', only: [:show], param: :username do
    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end

      resources :replies, only: [:index], module: :activitypub
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts
    resource :follow, only: [:create], controller: :account_follow
    resource :unfollow, only: [:create], controller: :account_unfollow

    resource :outbox, only: [:show], module: :activitypub
    resource :inbox, only: [:create], module: :activitypub
    resource :claim, only: [:create], module: :activitypub
    resources :collections, only: [:show], module: :activitypub
    resource :followers_synchronization, only: [:show], module: :activitypub
  end

  resource :inbox, only: [:create], module: :activitypub

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:username/with_replies', to: 'accounts#show', as: :short_account_with_replies
  get '/@:username/media', to: 'accounts#show', as: :short_account_media
  get '/@:username/tagged/:tag', to: 'accounts#show', as: :short_account_tag
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status
  get '/@:account_username/:id/embed', to: 'statuses#embed', as: :embed_short_account_status

  get  '/interact/:id', to: 'remote_interaction#new', as: :remote_interaction
  post '/interact/:id', to: 'remote_interaction#create'

  get '/explore', to: 'directories#index', as: :explore
  get '/settings', to: redirect('/settings/profile')

  namespace :settings do
    resource :profile, only: [:show, :update] do
      resources :pictures, only: :destroy
    end

    get :preferences, to: redirect('/settings/preferences/appearance')

    namespace :preferences do
      resource :appearance, only: [:show, :update], controller: :appearance
      resource :notifications, only: [:show, :update]
      resource :other, only: [:show, :update], controller: :other
    end

    resource :import, only: [:show, :create]
    resource :export, only: [:show, :create]

    namespace :exports, constraints: { format: :csv } do
      resources :follows, only: :index, controller: :following_accounts
      resources :blocks, only: :index, controller: :blocked_accounts
      resources :mutes, only: :index, controller: :muted_accounts
      resources :lists, only: :index, controller: :lists
      resources :domain_blocks, only: :index, controller: :blocked_domains
      resources :bookmarks, only: :index, controller: :bookmarks
    end

    resources :two_factor_authentication_methods, only: [:index] do
      collection do
        post :disable
      end
    end

    resource :otp_authentication, only: [:show, :create], controller: 'two_factor_authentication/otp_authentication'

    resources :webauthn_credentials, only: [:index, :new, :create, :destroy],
              path: 'security_keys',
              controller: 'two_factor_authentication/webauthn_credentials' do

      collection do
        get :options
      end
    end

    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :identity_proofs, only: [:index, :new, :create, :destroy]

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]
    resource :migration, only: [:show, :create]

    namespace :migration do
      resource :redirect, only: [:new, :create, :destroy]
    end

    resources :aliases, only: [:index, :create, :destroy]
    resources :sessions, only: [:destroy]
    resources :featured_tags, only: [:index, :create, :destroy]
    resources :login_activities, only: [:index]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]
  resource :relationships, only: [:show, :update]
  resource :statuses_cleanup, controller: :statuses_cleanup, only: [:show, :update]

  get '/public', to: 'public_timelines#show', as: :public_timeline
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :domain_allows, only: [:new, :create, :show, :destroy]
    resources :domain_blocks, only: [:new, :create, :show, :destroy, :update, :edit]

    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]

    resources :announcements, except: [:show] do
      member do
        post :publish
        post :unpublish
      end
    end

    resource :settings, only: [:edit, :update]
    resources :site_uploads, only: [:destroy]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ } do
      member do
        post :clear_delivery_errors
        post :restart_delivery
        post :stop_delivery
      end
    end

    resources :rules

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show, :destroy] do
      member do
        post :enable
        post :unsensitive
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :relationships, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role, only: [] do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
      resource :sign_in_token_authentication, only: [:create, :destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :ip_blocks, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]
    resource :follow_recommendations, only: [:show, :update]

    resources :tags, only: [:index, :show, :update] do

server/flow/ruby/app/models/instance.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: instances
#
#  domain         :string           primary key
#  accounts_count :bigint(8)
#

class Instance < ApplicationRecord
  self.primary_key = :domain

  attr_accessor :failure_days

  has_many :accounts, foreign_key: :domain, primary_key: :domain

  belongs_to :domain_block, foreign_key: :domain, primary_key: :domain
  belongs_to :domain_allow, foreign_key: :domain, primary_key: :domain
  belongs_to :unavailable_domain, foreign_key: :domain, primary_key: :domain # skipcq: RB-RL1031

  scope :matches_domain, ->(value) { where(arel_table[:domain].matches("%#{value}%")) }

  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: true, cascade: false)
  end

  def readonly?
    true
  end

  def delivery_failure_tracker
    @delivery_failure_tracker ||= DeliveryFailureTracker.new(domain)
  end

  def following_count
    @following_count ||= Follow.where(account: accounts).count
  end

  def followers_count
    @followers_count ||= Follow.where(target_account: accounts).count
  end

  def reports_count
    @reports_count ||= Report.where(target_account: accounts).count
  end

  def blocks_count
    @blocks_count ||= Block.where(target_account: accounts).count
  end

  def public_comment
    domain_block&.public_comment
  end

  def private_comment
    domain_block&.private_comment
  end

  def media_storage
    @media_storage ||= MediaAttachment.where(account: accounts).sum(:file_file_size)
  end

  def to_param
    domain
  end
end

server/flow/ruby/app/controllers/admin/instances_controller.rb
# frozen_string_literal: true

module Admin
  class InstancesController < BaseController
    before_action :set_instances, only: :index
    before_action :set_instance, except: :index
    before_action :set_exhausted_deliveries_days, only: :show

    def index
      authorize :instance, :index?
    end

    def show
      authorize :instance, :show?
    end

    def clear_delivery_errors
      authorize :delivery, :clear_delivery_errors?

      @instance.delivery_failure_tracker.clear_failures!
      redirect_to admin_instance_path(@instance.domain)
    end

    def restart_delivery
      authorize :delivery, :restart_delivery?

      last_unavailable_domain = unavailable_domain

      if last_unavailable_domain.present?
        @instance.delivery_failure_tracker.track_success!
        log_action :destroy, last_unavailable_domain
      end

      redirect_to admin_instance_path(@instance.domain)
    end

    def stop_delivery
      authorize :delivery, :stop_delivery?

      UnavailableDomain.create(domain: @instance.domain)
      log_action :create, unavailable_domain
      redirect_to admin_instance_path(@instance.domain)
    end

    private

    def set_instance
      @instance = Instance.find(params[:id])
    end

    def set_exhausted_deliveries_days
      @exhausted_deliveries_days = @instance.delivery_failure_tracker.exhausted_deliveries_days
    end

    def set_instances
      @instances = filtered_instances.page(params[:page])
      warning_domains_map = DeliveryFailureTracker.warning_domains_map

      @instances.each do |instance|
        instance.failure_days = warning_domains_map[instance.domain]
      end
    end

    def unavailable_domain
      UnavailableDomain.find_by(domain: @instance.domain)
    end

    def filtered_instances
      InstanceFilter.new(whitelist_mode? ? { allowed: true } : filter_params).results
    end

    def filter_params
      params.slice(*InstanceFilter::KEYS).permit(*InstanceFilter::KEYS)
    end
  end
end

server/flow/ruby/app/controllers/api/v1/instances/activity_controller.rb
# frozen_string_literal: true

class Api::V1::Instances::ActivityController < Api::BaseController
  before_action :require_enabled_api!

  skip_before_action :set_cache_headers
  skip_before_action :require_authenticated_user!, unless: :whitelist_mode?

  def show
    expires_in 1.day, public: true
    render_with_cache json: :activity, expires_in: 1.day
  end

  private

  def activity
    weeks = []

    12.times do |i|
      day     = i.weeks.ago.to_date
      week_id = day.cweek
      week    = Date.commercial(day.cwyear, week_id)

      weeks << {
        week: week.to_time.to_i.to_s,
        statuses: Redis.current.get("activity:statuses:local:#{week_id}") || '0',
        logins: Redis.current.pfcount("activity:logins:#{week_id}").to_s,
        registrations: Redis.current.get("activity:accounts:local:#{week_id}") || '0',
      }
    end

    weeks
  end

  def require_enabled_api!
    head 404 unless Setting.activity_api_enabled && !whitelist_mode?
  end
end

server/flow/ruby/app/controllers/api/v1/instances/peers_controller.rb
# frozen_string_literal: true

class Api::V1::Instances::PeersController < Api::BaseController
  before_action :require_enabled_api!

  skip_before_action :set_cache_headers
  skip_before_action :require_authenticated_user!, unless: :whitelist_mode?

  def index
    expires_in 1.day, public: true
    render_with_cache(expires_in: 1.day) { Instance.where.not(domain: DomainBlock.select(:domain)).pluck(:domain) }
  end

  private

  def require_enabled_api!
    head 404 unless Setting.peers_api_enabled && !whitelist_mode?
  end
end

server/flow/ruby/app/controllers/api/v1/instances/rules_controller.rb
# frozen_string_literal: true

class Api::V1::Instances::RulesController < Api::BaseController
  skip_before_action :require_authenticated_user!, unless: :whitelist_mode?

  before_action :set_rules

  def index
    render json: @rules, each_serializer: REST::RuleSerializer
  end

  private

  def set_rules
    @rules = Rule.ordered
  end
end

server/flow/ruby/app/controllers/api/v1/instances_controller.rb
# frozen_string_literal: true

class Api::V1::InstancesController < Api::BaseController
  skip_before_action :set_cache_headers
  skip_before_action :require_authenticated_user!, unless: :whitelist_mode?

  def show
    expires_in 3.minutes, public: true
    render_with_cache json: {}, serializer: REST::InstanceSerializer, root: 'instance'
  end
end

server/flow/ruby/app/helpers/instance_helper.rb
# frozen_string_literal: true

module InstanceHelper
  def site_title
    Setting.site_title
  end

  def site_hostname
    @site_hostname ||= Addressable::URI.parse("//#{Rails.configuration.x.local_domain}").display_uri.host
  end

  def description_for_sign_up
    prefix = begin
      if @invite.present?
        I18n.t('auth.description.prefix_invited_by_user', name: @invite.user.account.username)
      else
        I18n.t('auth.description.prefix_sign_up')
      end
    end

    safe_join([prefix, I18n.t('auth.description.suffix')], ' ')
  end
end

server/flow/ruby/app/views/admin/instances/_exhausted_deliveries_days.haml
%li.negative-hint
  = l(exhausted_deliveries_days)

server/flow/ruby/app/views/admin/instances/_instance.html.haml
.directory__tag
  = link_to admin_instance_path(instance) do
    %h4
      = instance.domain
      %small
        - if instance.domain_block
          - first_item = true
          - if !instance.domain_block.noop?
            = t("admin.domain_blocks.severity.#{instance.domain_block.severity}")
            - first_item = false
          - unless instance.domain_block.suspend?
            - if instance.domain_block.reject_media?
              - unless first_item
                &bull;
              = t('admin.domain_blocks.rejecting_media')
              - first_item = false
            - if instance.domain_block.reject_reports?
              - unless first_item
                &bull;
              = t('admin.domain_blocks.rejecting_reports')
        - elsif whitelist_mode?
          = t('admin.accounts.whitelisted')
        - else
          = t('admin.accounts.no_limits_imposed')
        - if instance.failure_days
          = ' / '
          %span.negative-hint
            = t('admin.instances.delivery.warning_message', count: instance.failure_days)
        - if instance.unavailable_domain
          = ' / '
          %span.negative-hint
            = t('admin.instances.delivery.unavailable_message')
    .trends__item__current{ title: t('admin.instances.known_accounts', count: instance.accounts_count) }= friendly_number_to_human instance.accounts_count

server/flow/ruby/app/views/admin/instances/index.html.haml
- content_for :page_title do
  = t('admin.instances.title')

- content_for :heading_actions do
  - if whitelist_mode?
    = link_to t('admin.domain_allows.add_new'), new_admin_domain_allow_path, class: 'button'
  - else
    = link_to t('admin.domain_blocks.add_new'), new_admin_domain_block_path, class: 'button'

.filters
  .filter-subset
    %strong= t('admin.instances.moderation.title')
    %ul
      %li= filter_link_to t('admin.instances.moderation.all'), limited: nil

      - unless whitelist_mode?
        %li= filter_link_to t('admin.instances.moderation.limited'), limited: '1'

  .filter-subset
    %strong= t('admin.instances.delivery.title')
    %ul
      %li= filter_link_to t('admin.instances.delivery.all'), warning: nil, unavailable: nil
      %li= filter_link_to t('admin.instances.delivery.warning'), warning: '1', unavailable: nil
      %li= filter_link_to t('admin.instances.delivery.unavailable'), warning: nil, unavailable: '1'

  .back-link
    = link_to admin_instances_path() do
      %i.fa.fa-chevron-left.fa-fw
      = t('admin.instances.back_to_all')
    = link_to admin_instances_path(limited: 1) do
      %i.fa.fa-chevron-left.fa-fw
      = t('admin.instances.back_to_limited')
    = link_to admin_instances_path(warning: 1) do
      %i.fa.fa-chevron-left.fa-fw
      = t('admin.instances.back_to_warning')

- unless whitelist_mode?
  = form_tag admin_instances_url, method: 'GET', class: 'simple_form' do
    .fields-group
      - InstanceFilter::KEYS.each do |key|
        = hidden_field_tag key, params[key] if params[key].present?

      - %i(by_domain).each do |key|
        .input.string.optional
          = text_field_tag key, params[key], class: 'string optional', placeholder: I18n.t("admin.instances.#{key}")

      .actions
        %button.button= t('admin.accounts.search')
        = link_to t('admin.accounts.reset'), admin_instances_path, class: 'button negative'

%hr.spacer/

- if @instances.empty?
  %div.muted-hint.center-text
    = t 'admin.instances.empty'
- else
  = render partial: 'instance', collection: @instances

= paginate @instances

server/flow/ruby/app/views/admin/instances/show.html.haml
- content_for :page_title do
  = @instance.domain

.filters
  .back-link
    = link_to admin_instances_path() do
      %i.fa.fa-chevron-left.fa-fw
      = t('admin.instances.back_to_all')
    = link_to admin_instances_path(limited: 1) do
      %i.fa.fa-chevron-left.fa-fw
      = t('admin.instances.back_to_limited')
    = link_to admin_instances_path(warning: 1) do
      %i.fa.fa-chevron-left.fa-fw
      = t('admin.instances.back_to_warning')

.dashboard__counters
  %div
    = link_to admin_accounts_path(remote: '1', by_domain: @instance.domain) do
      .dashboard__counters__num= number_with_delimiter @instance.accounts_count
      .dashboard__counters__label= t 'admin.accounts.title'
  %div
    = link_to admin_reports_path(by_target_domain: @instance.domain) do
      .dashboard__counters__num= number_with_delimiter @instance.reports_count
      .dashboard__counters__label= t 'admin.instances.total_reported'
  %div
    %div
      .dashboard__counters__num= number_to_human_size @instance.media_storage
      .dashboard__counters__label= t 'admin.instances.total_storage'
  %div
    %div
      .dashboard__counters__num= number_with_delimiter @instance.following_count
      .dashboard__counters__label= t 'admin.instances.total_followed_by_them'
  %div
    %div
      .dashboard__counters__num= number_with_delimiter @instance.followers_count
      .dashboard__counters__label= t 'admin.instances.total_followed_by_us'
  %div
    %div
      .dashboard__counters__num= number_with_delimiter @instance.blocks_count
      .dashboard__counters__label= t 'admin.instances.total_blocked_by_us'

  %div
    %div
      .dashboard__counters__num
        - if @instance.delivery_failure_tracker.available?
          = fa_icon 'check'
        - else
          = fa_icon 'times'
      .dashboard__counters__label= t 'admin.instances.delivery_available'

- if @instance.private_comment.present?
  .speech-bubble
    .speech-bubble__bubble
      = simple_format(h(@instance.private_comment))
    .speech-bubble__owner= t 'admin.instances.private_comment'

- if @instance.public_comment.present?
  .speech-bubble
    .speech-bubble__bubble
      = simple_format(h(@instance.public_comment))
    .speech-bubble__owner= t 'admin.instances.public_comment'

- unless @exhausted_deliveries_days.empty?
  %h4= t 'admin.instances.delivery_error_days'
  %ul
    = render partial: 'exhausted_deliveries_days', collection: @exhausted_deliveries_days
  %p.hint
    = t 'admin.instances.delivery_error_hint', count: DeliveryFailureTracker::FAILURE_DAYS_THRESHOLD

%hr.spacer/

%div.action-buttons
  %div
    - if @instance.domain_allow
      = link_to t('admin.domain_allows.undo'), admin_domain_allow_path(@instance.domain_allow), class: 'button button--destructive', data: { confirm: t('admin.accounts.are_you_sure'), method: :delete }
    - elsif @instance.domain_block
      = link_to t('admin.domain_blocks.edit'), edit_admin_domain_block_path(@instance.domain_block), class: 'button'
      = link_to t('admin.domain_blocks.undo'), admin_domain_block_path(@instance.domain_block), class: 'button'
    - else
      = link_to t('admin.domain_blocks.add_new'), new_admin_domain_block_path(_domain: @instance.domain), class: 'button'
    - if @instance.delivery_failure_tracker.available?
      - unless @exhausted_deliveries_days.empty?
        = link_to t('admin.instances.delivery.clear'), clear_delivery_errors_admin_instance_path(@instance), data: { confirm: t('admin.accounts.are_you_sure'), method: :post }, class: 'button'
      = link_to t('admin.instances.delivery.stop'), stop_delivery_admin_instance_path(@instance), data: { confirm: t('admin.accounts.are_you_sure'), method: :post }, class: 'button'
    - else
      = link_to t('admin.instances.delivery.restart'), restart_delivery_admin_instance_path(@instance), data: { confirm: t('admin.accounts.are_you_sure'), method: :post }, class: 'button'